import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabaseClient'
import { Users, Plus, Edit2, Trash2, X, Check } from 'lucide-react'
const empty = { username:'', email:'', password:'', role:'kasir' }
export default function Settings() {
  const [users,setUsers]=useState([]); const [load,setLoad]=useState(true)
  const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState(null)
  const [fd,setFd]=useState(empty); const [msg,setMsg]=useState({type:'',text:''})
  useEffect(()=>{ run() },[])
  async function run(){ const {data,error}=await supabase.from('users').select('id, username, email, role, is_active').order('username'); if(error) setMsg({type:'error',text:error.message}); setUsers(data||[]); setLoad(false) }
  async function submit(e){ e.preventDefault(); setMsg({type:'',text:''}); try { if(editing){ const upd={ username:fd.username, email:fd.email, role:fd.role }; if(fd.password) upd.password=fd.password; const {error}=await supabase.from('users').update(upd).eq('id',editing.id); if(error) throw error; setMsg({type:'success',text:'User diupdate'}) } else { if(!fd.password){ setMsg({type:'error',text:'Password wajib diisi'}); return } const {error}=await supabase.from('users').insert({ username:fd.username, email:fd.email, password:fd.password, role:fd.role, is_active:true }); if(error) throw error; setMsg({type:'success',text:'User ditambahkan'}) } setShowForm(false); setEditing(null); setFd(empty); run(); setTimeout(()=>setMsg({type:'',text:''}),3000) } catch(err){ setMsg({type:'error',text:err.message}) } }
  async function del(id){ if(!confirm('Hapus user ini?'))return; const {error}=await supabase.from('users').delete().eq('id',id); if(error) setMsg({type:'error',text:error.message}); else setMsg({type:'success',text:'User dihapus'}); run(); setTimeout(()=>setMsg({type:'',text:''}),3000) }
  function edit(u){ setEditing(u); setFd({ username:u.username, email:u.email||'', password:'', role:u.role }); setShowForm(true) }
  function add(){ setEditing(null); setFd(empty); setShowForm(true) }
  const badge = r => { const c={owner:'bg-[#0058A3] text-white',kasir:'bg-blue-100 text-[#0058A3]',gudang:'bg-gray-100 text-gray-700'}; return <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${c[r]||c.kasir}`}>{r.toUpperCase()}</span> }
  if(load) return <div className="p-8 flex justify-center"><div className="w-8 h-8 border-4 border-[#0058A3] border-t-transparent rounded-full animate-spin"/></div>
  return (
    <div className="p-6 lg:p-8">
      <div className="flex justify-between items-center mb-6"><div><h2 className="text-2xl font-bold text-gray-900">Pengaturan</h2><p className="text-sm text-gray-500 mt-0.5">Manajemen user & hak akses</p></div><button onClick={add} className="flex items-center gap-2 px-4 py-2 bg-[#0058A3] text-white rounded-lg hover:bg-[#004080] shadow-sm"><Plus className="w-4 h-4"/><span className="text-sm font-medium">Tambah User</span></button></div>
      {msg.text&&<div className={`mb-4 px-4 py-3 rounded-lg text-sm animate-fade-in ${msg.type==='success'?'bg-green-50 text-green-700 border border-green-200':'bg-red-50 text-red-700 border border-red-200'}`}>{msg.text}</div>}
      {showForm&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 animate-fade-in"><div className="bg-white rounded-xl shadow-2xl w-full max-w-md"><div className="flex justify-between items-center p-6 border-b"><h3 className="font-bold text-lg">{editing?'Edit User':'Tambah User Baru'}</h3><button onClick={()=>setShowForm(false)} className="p-1 hover:bg-gray-100 rounded"><X className="w-5 h-5"/></button></div>
        <form onSubmit={submit} className="p-6 space-y-4">
          <div><label className="block text-sm font-medium text-gray-700 mb-1.5">Username *</label><input type="text" required value={fd.username} onChange={e=>setFd({...fd,username:e.target.value})} className="w-full px-4 py-2.5 border rounded-lg outline-none" placeholder="Nama pengguna"/></div>
          <div><label className="block text-sm font-medium text-gray-700 mb-1.5">Email (Opsional)</label><input type="email" value={fd.email} onChange={e=>setFd({...fd,email:e.target.value})} className="w-full px-4 py-2.5 border rounded-lg outline-none" placeholder="email@fancell.com"/></div>
          <div><label className="block text-sm font-medium text-gray-700 mb-1.5">Password {editing?'(kosongkan jika tidak diubah)':'*'}</label><input type="password" required={!editing} value={fd.password} onChange={e=>setFd({...fd,password:e.target.value})} className="w-full px-4 py-2.5 border rounded-lg outline-none" placeholder="Minimal 6 karakter" minLength={6}/></div>
          <div><label className="block text-sm font-medium text-gray-700 mb-1.5">Role / Hak Akses *</label><select value={fd.role} onChange={e=>setFd({...fd,role:e.target.value})} className="w-full px-4 py-2.5 border rounded-lg bg-white"><option value="owner">Owner (Akses Penuh)</option><option value="kasir">Kasir (Transaksi & Stok)</option><option value="gudang">Gudang (Master Barang Saja)</option></select><p className="text-xs text-gray-500 mt-1">{fd.role==='owner'?'Semua modul termasuk Laba Rugi & Pengaturan':fd.role==='kasir'?'POS, Riwayat, Barang (tanpa Laba Rugi)':'Master Barang saja'}</p></div>
          <div className="flex gap-3 pt-2"><button type="button" onClick={()=>setShowForm(false)} className="flex-1 px-4 py-2.5 border text-gray-700 rounded-lg hover:bg-gray-50 font-medium">Batal</button><button type="submit" className="flex-1 px-4 py-2.5 bg-[#0058A3] text-white rounded-lg hover:bg-[#004080] font-medium flex items-center justify-center gap-2"><Check className="w-4 h-4"/>{editing?'Update':'Simpan'}</button></div>
        </form></div></div>}
      <div className="bg-white rounded-xl border shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-gray-50 border-b text-xs font-semibold text-gray-500 uppercase"><th className="text-left p-3">User</th><th className="text-left p-3">Email</th><th className="text-left p-3">Role</th><th className="text-left p-3">Hak Akses</th><th className="text-right p-3">Aksi</th></tr></thead>
        <tbody className="divide-y">{users.map(u=>(<tr key={u.id} className="hover:bg-gray-50"><td className="p-3"><div className="flex items-center gap-3"><div className="w-9 h-9 bg-gradient-to-br from-[#0058A3] to-[#004080] rounded-full flex items-center justify-center font-bold text-white text-sm">{u.username?.charAt(0).toUpperCase()}</div><span className="text-sm font-medium">{u.username}</span></div></td><td className="p-3 text-sm text-gray-600">{u.email||'-'}</td><td className="p-3">{badge(u.role)}</td><td className="p-3 text-xs text-gray-500">{u.role==='owner'?'Semua modul':u.role==='kasir'?'POS, Riwayat, Barang':'Master Barang saja'}</td><td className="p-3 text-right"><div className="flex justify-end gap-2"><button onClick={()=>edit(u)} className="p-1.5 hover:bg-blue-50 rounded text-[#0058A3]"><Edit2 className="w-4 h-4"/></button><button onClick={()=>del(u.id)} className="p-1.5 hover:bg-red-50 rounded text-red-600"><Trash2 className="w-4 h-4"/></button></div></td></tr>))}</tbody></table></div></div>
    </div> )
}
